
:::{.box .bs-right}

# Voting and Constitutional Convention
:::

:::{.box .bs-bottom }


:::{.text-center}
Section 1
:::

Following a motion by the leader of the house to transition to the Second Republic a round of voting shall happen. If three quarter of the house shall vote in the yes, to transition to the Second Republic then a process called the constitutional convention shall start. During the period of the constitutional convention, the state shall run on the old constitution with the old laws. The constitutional convention shall open this constitution to the scrutiny of all and need the co-operation of all parties in parliament to fill the remaining gaps present so that it may be used as a precise foundation for the Second Republic. 

All the additional laws that will be most necessary so we may transition, to a precisely defined Second Republic shall be referred to as organic laws, and will be kept separate from this main constitution so as to always encourage every citizen to take the time to read it owing to its short nature, to learn of the rules governing them and of their rights.


:::{.text-center}
Section 2
:::

To be deemed an organic Law, a bill shall need the concurrence of three quarters of the National Assembly. Likewise modifying an organic law will have you needing to wield three quarters of the votes in the National Assembly. All organic laws will need to be verified as to their precision and correctness, by the Supreme Court, vis a vis their need to exist expounded by the original constitution, before they can be officially promulgated.

:::{.text-center}
Section 3
:::

To become the official consitution of the Republic of Mauritius after the constitutional convention, the population will need to vote on the matter via referendum. If a majority shall vote in the yes, We shall be governed by the new constitution and its organic laws.

:::{.text-center}
Section 4
:::

The National Assembly whenever four fifths shall deem it necessary, shall propose amendments to this constitution. The sitting President's duty shall be to educate his people in good faith, on the exact implications of such amendments for six months. His purse to do so shall be adequate. The people shall vote after six months after the day the amedements shall have been proposed. If a majority of the population votes in the yes, the amendments shall pass. 

:::{.text-center}
Miscellaneous
:::

The Government of the Second Republic of Mauritius shall in good faith carry forward and take the burden of all the debts and liabilities of the First Republic of Mauritius.

:::
