

:::{.box .bs-right}

# Decentralization
:::


:::{.box .bs-bottom }


:::{.text-center} 
Section 1
:::

The Republic of Mauritius shall be a union of the citizens of this land. The sovereignty of this land shall reside in the people and all authority shall emanate from them solely. The word ''Mauritius'' shall be construed to mean The Republic of Mauritius throughout this constitution. The territory of Mauritius shall consist of the island of Mauritius and Rodrigues together with other smaller islands belonging justly to it as well as its maritime space. The will of the people shall be expressed by referendums and shall be Supreme. 

:::{.text-center} 
Section 2
:::

The Government of Mauritius shall be separated into a state government and local governments. The state government shall have three branches. The executive which a President shall head, the legislative which shall consist of a National Assembly, and the judiciary which shall consist of one Supreme Court and inferior courts. These three branches shall be separate and distinct, so that neither exercise the powers properly belonging to the others. 

:::{.text-center} 
Section 3
:::

All executive agencies shall be created by acts of the National Assembly. The President may from time to time re-organise his executive departments or seek creation of an agency if his changes be approved by two thirds of the National Assembly.

:::{.text-center} 
Section 4
:::

This constitution is the Supreme law of Mauritius and if any other law applicable in the land is believed by a citizen to be inconsistent with this constitution, and the application of it affects said citizen's life. Such a citizen shall be entitled to challenge the law in any court of Mauritius he may deem fit. The same shall apply to businesses. 

No district shall make or enforce any law which shall abridge the privileges or immunities of citizens of Mauritius given by this constitution and the judges in every district shall be bound to this constitution and all the laws of the State anything to the contrary in the laws of districts notwithstanding.

:::{.text-center} 
Section 5
:::

Mauritius shall be divided into districts with each one being a distinct local level of government. Each district shall have a mayor who shall be chief executive, a district council who shall be its legislature, a district attorney who shall be its local judiciary representative and any other local officer as may be ascertained by Law. All shall be elected by direct popular vote by the citizens in their respective districts, as per the common district charter prescribed by the National Assembly, which all districts shall be bound to in their running.

:::{.text-center} 
Section 6
:::

Each district shall have its own autonomy to run its day to day administration, property and affairs.


:::{.text-center} 
Section 7
:::

Each District shall have its own representative of the Judiciary in a District Attorney who shall in good faith, defend and represent the citizens of that district.^[The State counsel office controlled by the Prime Minister will no longer be able to prevent any drug traffickers from escaping the law this way, especially if DA's want to get re-elected. This guarantees that the Judiciary will have some incentive to do their job for relection.]

Every District shall have a uniform court system, which ultimately shall have as highest court the state supreme court.

No District shall have a supreme court but the state alone shall have one supreme court with as many divisions as the National Assembly shall think necessary to make justice more fluid and efficient over time.

An Attorney General nominated by the President with confirmation of two thirds of the National Assembly shall be the public prosecutor of the state, who shall in good faith, defend and represent the state.^[This will replace the DPP. The neccessary and proper clause empowers parliament to decide what powers and duties exactly the Attorney General will have.]



:::{.text-center} 
Section 8
:::

The finances, procurements, financial position, effective real time status and productive capacity of the entire Republic shall be clear and intelligible and always accessible to every man in the Republic. So that they may comprehend them, investigate them to prevent abuses and in the case of procurements, also contest them.

:::{.text-center} 
Section 9
:::

Obstructing the accurate carrying out of the government processes enumerated in this constitution, shall constitute a crime to be ascertained appropriately by law.^[This paragraph aided by the one before it would imprison people who would dare fake all kinds of statistics, something which is common worldwide and not a crime.]

:::{.text-center} 
Section 10
:::

The powers not delegated to the State by this Constitution, nor prohibited by it to the Districts, are reserved to the Districts respectively, or to the people.^[This paragraph gives police powers to the districts because such power is not attributed to the state government in this constitution, effectively decentralising the police permanently. ]

:::