
:::{.box .bs-right}

# The Executive Branch
:::

:::{.box .bs-bottom}

:::{.text-center}
Section 1
:::

The executive power shall be vested in a President of the Republic of Mauritius.

:::{.text-center}
Section 2
:::

The President shall be Commander in Chief of the para-military forces of Mauritius. 

:::{.text-center}
Section 3
:::

He shall have Power to grant Reprieves and Pardons for Offenses against Mauritius, except in Cases of Impeachment. 

:::{.text-center}
Section 4
:::

He shall have Power, by and with the Advice and Consent of the National Assembly, to make Treaties, provided two thirds of the National Assembly present concur.

He shall nominate, and by and with the Advice and Consent of the National Assembly, shall appoint Ambassadors, the Chief Justice of the Supreme Court, the Governor of the Central Bank of Mauritius and all other officers of Mauritius, whose Appointments are not herein otherwise provided for, and which shall be established by Law: but the National Assembly may by Law vest the Appointment of such inferior Officers, as they think proper, in the President alone, in the Courts of Law, or in the Heads of Departments.^[Parliament decides, with their law making power, what concensus will be needed for all nominations. Not the President. The President follows the laws which parliament makes.]

He shall send his budget proposal to the National Assembly every year to start the process of funding the Government which shall likewise a bill end with him for approval or a two thirds vote superseding his will.^[President is responsible for pitching his vision and therefore his budget to the house every year.]

He shall from time to time give to the National Assembly information of the state of the Republic, and recommend to their consideration such measures as he shall judge necessary and expedient.^[Yearly addresses to the population on television, mostly]

He may, on extraordinary Occasions, convene the National Assembly, with Respect to the time of Adjournment, he may adjourn them to such time as he shall think proper.

He shall receive Ambassadors and other public Ministers.

He shall take Care that the Laws be faithfully executed, and shall Commission all the Officers of Mauritius.

As the leader of the Executive branch and the State, and to ensure laws be faithfully executed, no one in public or para-public service shall earn more in aggregate pay or fixed pay than the President of Mauritius.


:::