

:::{.box .bs-right}

# Impeachment 
:::

:::{.box .bs-bottom }

:::{.text-center}
Section 1
:::

Impeachment need not be beyond a reasonable doubt.

:::{.text-center}
Section 2
:::

The President and all civil Officers of the Republic of Mauritius, shall be removed from Office on Impeachment for, and Conviction of, Treason , Bribery, or other high Crimes and Misdemeanors.

:::{.text-center}
Section 3
:::

All local level government representatives elected by the people of Mauritius, shall be impeachable in a manner that is ascertained by Law. All local level government representatives may be recalled by a uniform procedure that shall be ascertained by Law.


:::{.text-center}
Section 4
:::

The Supreme Court shall have the sole Power to try all Impeachments. When the President of Mauritius is tried, the Chief Justice shall preside, and no Person shall be convicted without the Concurrence of a majority of the Justices in service.

Judgment in Cases of Impeachment shall not extend further than to removal from Office, but the Party convicted shall nevertheless be liable and subject to Indictment, Trial, Judgment and Punishment, according to Law.


:::{.text-center}
Section 5
:::

A rightfully impeached or expelled representative of the people is denied any form of state paid pension. Plus he may not represent the people again in any election for a period of 10 years, nor enjoy any office of honor, Trust or Profit under Mauritius.

:::