
:::{.box .bs-right}

# The Legislative Branch
:::

:::{.box .bs-bottom }

:::{.text-center}
Section 1
:::

All legislative Powers herein granted shall be vested in a single house called the National Assembly.

:::{.text-center}
Section 2
:::

The National Assembly shall have power to investigate all affairs of the entire Republic in order to be able to effectively carry its legislative function.


:::{.text-center}
Section 2
:::

The National Assembly and The President shall be bound by the maxim of "Securing Life, Liberty, and the Rights of the people in their pursuit of Happiness" in the case mentioned below. 

Any law or circumstance meeting all the following conditions unequivocally, first that the law or circumstance in controversy shall concern civil rights, second that the law or circumstance in controversy shall be to the detriment of the exercising of civil rights of a distinct group in the Republic, and lastly while at the same time being favorable to the majority group, shall point to a law that is a reflection of a tyranny of the majority and shall therefore be redressed by the legislature or the executive so that they may fulfill their maxim.^[Communalism will be virtually impossible with this. So you have nothing to fear. What you have feared all your life because of the fear mongering of politicians. Si un tel vine premier minis, li pa pou donne malbar nanien. All of that will be in the past going forward. We will all be equals. Even you, the one from the minority group, you will finally get your house from the NHDC. ]


:::{.text-center}
Section 3
:::

The National Assembly shall choose their Speaker and other Officers; and shall have the sole Power of Impeachment.

:::{.text-center}
Section 4
:::

The National Assembly may determine the Rules of its Proceedings, punish its Members for disorderly Behaviour, and, with the Concurrence of two thirds, expel a Member.

A Majority shall constitute a Quorum to do Business; but a smaller Number may adjourn from day to day, and may be authorized to compel the Attendance of absent Members, in such Manner, and under such Penalties as each House may provide.

It shall keep a Journal of its Proceedings, and from time to time publish the same, excepting such Parts as may in their Judgment require Secrecy; and the Yeas and Nays of the Members of either House on any question shall, at the Desire of one fifth of those Present, be entered on the Journal.


:::{.text-center}
Section 5
:::

All bills to raise revenue shall originate from the National Assembly.

Every bill shall have a title which matches its soul (singular). The title shall be considered a set by which its finite subsets shall intuitively follow. A set which shall contain the possibility of infinite subsets shall be called an omnibus bill.

It shall be at the President's sole discretion when an omnibus bill is sent to him to decide whether to consider the bill or to veto it. An Omnibus bill shall only supersede the president's veto if it is voted unanimously by the entire National Assembly.^[Finance bills which will get your name off the registered voters list, like was done prior to the 2019 elections for minorities, will be virtually impossible in the future, with this paragraph aided by the one before it.]

Every bill shall need to have the vote of 3/5 of the National Assembly to warrant the bill's passage to its next step which shall be to send the bill to the president for his approval and signing. If he approves he shall sign it and the bill shall become law, but if not he shall return it, along with his objections to the house who shall proceed to enter the objections at large on their journal and proceed to reconsider it. If after such reconsideration two thirds of the house shall vote to pass the bill, it shall become law.^[Promotes bipartisanship by requiring more than simple majority]

Every order, resolution, or vote to which the concurrence of the National Assembly may be necessary shall be presented to the President of Mauritius; and before the same shall take effect, shall be approved by him, or being disapproved by him, shall be repassed by two thirds of the National Assembly, according to the rules and limitations prescribed in the case of a bill.


:::{.text-center}
Section 6
:::

Members of the National Assembly shall in all Cases, except Treason, Felony and Breach of the Peace, be privileged from Arrest during their Attendance at the Session of the House, and in going to and returning from the same; and for any Speech or Debate in the House, they shall not be questioned in any other Place.

No member of the National Assembly shall, during the Time for which he was elected, be appointed to any civil Office under the Authority of Mauritius; and any Person holding any Office for Profit under Mauritius during their tenure shall have its **income** incumber a special tax called the corruption tax at the rate of 90\%, to make stealing an unproductive endeavor, during their Continuance in Office.^[This amendement kills the Tamano's and Toopun's of this world we live in. Stealing would effectively, push their tax bills astronomically high, making holding any office for profit unlikely during their continuance in office. They will be forced to give back 900,000 Rs for every 1,000,000 Rs they steal.] 

:::{.text-center}
Section 7
:::

The National Assembly shall have power to lay and collect taxes, duties, imposts and excises, to pay the debts and provide for the common defense and general welfare of Mauritius.

To borrow money on the credit of Mauritius.^[It will become impossible to take debt by the executive without parliament's co-operation which is not the case now.]

To regulate commerce with foreign nations and among the several districts.

To establish a uniform rule of naturalization, and a singular source of law on the subject of bankruptcies, corporations, crimes and civil disagreements which shall be applicable in Mauritius.^[Setup to transition to modern penal, civil and corporate codes]

To give the people of this Republic a choice to make their new source of law ex-post facto law.^[Retributive Justice.]

To create a uniform charter so local governments can have proper autonomy and empower them with impeachment, rule making and decentralisation powers proper to them.

To empower the people of each district with recall powers so they may prevent abuses locally.

To properly decentralize district jurisdictions but ensure state and inter-district co-operation, as well as state intervention only through regulations.^[Parliament will be able to regulate police co-operation from this, not the police itself]

To constitute tribunals inferior to the Supreme Court.

To coin money, regulate the value thereof, and of foreign coin, and fix the standard of weights and measures.

To provide for the punishment of counterfeiting the securities and current coin of Mauritius.

To promote the progress of science and useful arts, by securing for limited times to authors and inventors the exclusive right to their respective writings and discoveries.

To establish Post Offices.

To provide the funding required and the rules required for the obtaining those funds for the good running of all districts and regulations so they be accountable to the state.^[Bind districts to rules. Useful to set standards where education is concerned, standards where policing is concerned with stuff like police-cams, police footage etc..]

To define and punish crimes committed on the maritime space of the Republic.

To declare War.^[Unlikely we will ever declare war.]

To provide and maintain any form of militia.

To provide, regulate and maintain National Security, Intelligence, Crime and Corruption agencies.^[Alternatives to ICAC, NSS, SMF which would be highly regulated by Parliament]

To make rules for the Government and Regulation of any Land and Naval militia.^[Introduction of Military Service as an alternative career choice for people, We already have this informally, we will just formally call it the military now. Military service is a voluntary career choice not a compulsory thing.]

To provide for calling forth the Militia to execute the Laws of the Republic, suppress Insurrections and repel Invasions.

To make all Laws which shall be necessary and proper for carrying into Execution the foregoing Powers, and all other Powers vested by this Constitution in the Government of Mauritius, or in any Department or Officer thereof.^[This makes parliament the most powerful branch in the State Government.]

:::{.text-center}
Section 7
:::

The privilege of the writ of habeas corpus shall not be suspended, unless when in cases of rebellion or invasion, the public safety may require it.

No ex post facto Law shall be passed unless the principle of Res Ipsa Loquitor holds as to the inadequateness of any law's past iteration.^[Ex post facto law will only be passed, if the past iteration of the law, is **obviously negligently set up to work against the law's ability to consistently secure Justice.** ]

Ex post facto Law shall be used solely to prosecute past cases of Corruption, Collusion and Abuse of power (market or human) that happened in the First Republic of Mauritius.

No Money shall be drawn from the Treasury, but in Consequence of Appropriations made by Law. and a regular Statement and Account of the Receipts and Expenditures of all public Money shall be published from time to time by the various components of the Government of Mauritius.

:::