
:::{.box .bs-right}

# We The People
:::


:::{.box .bs-bottom }
:::{.center}
## PREAMBLE 
:::
We The People of The Republic of Mauritius reaffirm these truths to be self-evident, that all men are created equal, that they are endowed by the creator of the Universe with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness. That to secure these rights Governments are instituted among men, deriving their power from the consent of the governed. That, that is far from an ideal solution given all men are subject to bouts of madness, and so to limit the chances of government becoming destructive to these ends a maxim for the people of this land warrants specification to guide them at all times. The duty of the people this land shall be to uphold Republicanism :-

By making it possible for the human to discover themselves through public education. 

By always petitioning to spend as much as needed to ensure public education is of highest quality to ensure equal opportunities and independent thinking.

By favoring individualism.

By ensuring religion is kept separated from the state at all times especially when it concerns politics.

By voting whoever they want to vote in every election they are subject to. 

By always being on the lookout for corruption and doing their best to make government always uphold justice equally for all. 

By respecting their fellow men no matter what petty differences separates them. 

By always petitioning for constitutional amendments rather than use force if the times warrant it. 

By always making your highest priority maintaining the union together at all times no matter who or what the threat is.

By understanding the importance of the **correct functioning** of the rule of law among humans.

There will always be corruption. There will always be injustices. There will always be discrimination. Yet, if you the people do your absolute best to try to uphold republicanism, you will keep government on its toes. You will minimize corruption, injustice and discrimination to their bare minimum. Because although we humans have no morality.

The very creation of society bounds morality upon us all through fair and abundant competition. The rule of law formalizes that morality. The look of the other. How the other will see us. How society will perceive you. If you the people will be the force that opposes corruption, injustice and discrimination by constantly upholding the rule of law equally for all. You will have real democracy. That is what republicanism is. That is the duty, you the people will have to always uphold, in democracy that is instigated by the people for the people, if you want it to last and be a real democracy. Rather than an illusory one.


If and only if that is not enough, and you see that your pursuit of life, liberty and happiness is being trampled on by Government then by all means do what you must as a nation, so help you God.


To that end, We the People of the Republic of Mauritius in order to form a more perfect Union, establish Justice, insure domestic Peace, provide for common defence, promote the general Welfare, secure the blessings of Liberty to ourselves and our Posterity as well as make republicanism as natural as humanly possible, do ordain and establish this constitution of the Second Republic of Mauritius.


:::