:::{.box .bs-right}

# The Rights of The People
:::

:::{.box .bs-bottom}

:::{.text-center}
Section 1
:::

All persons born or naturalized in Mauritius, and subject to the jurisdiction thereof, are citizens of Mauritius.

None shall deprive any person of life, liberty, or property, without due process of law; nor deny to any person the equal protection of the laws of Mauritius.^[Due process of law does not currently exist in the Republic of Mauritius. For example, arbitrary arrests frequently do not proceed to the next legal step required by law, which is the right to the presence of a counsel for legal assitance. They rather proceed to the intimidation step by violating the due process of law. This is a simple example that has been perpetuated for 56 years with 'Ti-Dimoune' and enemies of government's in power.]


:::{.text-center}
Section 2
:::

The National Assembly shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble.^[ This will end ICTA's reign of terror.]

:::{.text-center}
Section 3
:::

The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized.^[This will end the SST's reign of terror.]

:::{.text-center}
Section 4
:::

No person shall be held to answer for a capital, or otherwise infamous crime, unless on a presentment or indictment of a Grand Jury; nor shall any person be subject for the same offence to be twice put in jeopardy of life or limb; nor shall be compelled in any criminal case to be a witness against himself; nor shall private property be taken for public use, without just compensation.^[This allows you to plead the fifth and will allow people who were coerced into providing self-incrinating confessions obtained through torture, a classic in our lovely country, to get their day in court.]

:::{.text-center}
Section 5
:::

In all criminal prosecutions, the accused shall enjoy the right to a speedy and public trial, by an impartial jury of the district wherein the crime shall have been committed, which district shall have been previously ascertained by law, and to be informed of the nature and cause of the accusation; to be confronted with the witnesses against him; to have compulsory process for obtaining witnesses in his favor, and to have the Assistance of Counsel for his defense paid by the state if he so needs.

:::{.text-center}
Section 6
:::

In Suits at common law, where the value in controversy shall be above one thousand rupees, the right of trial by jury shall be preserved, and no fact tried by a jury, shall be otherwise reexamined in any Court of Mauritius, than according to the rules of the common law.

:::{.text-center}
Section 7
:::

Excessive bail shall not be required, nor excessive fines imposed, nor cruel and unusual punishments inflicted.


:::{.text-center}
Section 8
:::

Any person, in case he is acquitted after he has been wrongfully arrested or detained, may sue the State for redress as ascertained by law.^[This would effectively cease all police torture because their pockets would become liable.]

Any law enforcement officer found guilty of violating the due process of law when it concerns the rights of a person shall be liable to pay 10\% percent of the state's compensation to the citizen as redress out of their pocket, or salary in installments or deducted against their future pensions for each count they may be liable to during their service in law enforcement.

:::{.text-center}
Section 9
:::

The age where a citizen can be deemed old enough to consent to sexual intercourse shall be set at eighteen years.^[It is currently 16. I am a conservative but liberal person I guess.]

A Romeo and Juliet clause shall be allowed where the difference of the absolute value of the two ages in controversy shall be at most 2.^[Don't mess with kids if you are no longer one.]

:::{.text-center}
Section 10
:::

The citizens shall pay to have information and unbiased education provided on public radio and television and therefore shall be entitled to have them be free from partisanship of any kind and propaganda.^[I will transition the MBC to a PBS style educative focused television channel. We will also focus on creating TV shows that espouses our history in French and English and do our best to export it. We can create a lot of colonial fiction for example and sell it to both the UK market and the French market. I am sure there are talented screen writers in the country.]

:::{.text-center}
Section 11
:::

The enumeration in this Constitution, of certain rights, shall not be construed to deny or disparage others retained by the people such as but not limited to; the protection of the people against slavery and involuntary servitude, the right to move at will and enjoy freedom of residence, freedom of occupation, freedom of learning and the arts, the right to private property, the right to privacy and any other self evident right.^[Thought of a self evident right that I did not cover? This section covers it informally.]



:::