---
format: 
  html:
    page-layout: full
---
:::{.box .bs-right}

# WHY LAVENIR MORIS?
:::

:::{.box .bs-bottom}

I never told anyone this because it is an embarassing secret, but my dream as a kid was weird. I wanted to become the President of the United States to make a utopic world real. I was a dumb kid back then, but I understood the position of the US in the world somehow. I was also drawn to power for some reason. Eventually, I got the internet and googled how to become president USA and that was when my dreams got shattered. You had to be a natural born citizen of the US to be President. Today, I know world peace is not in the books for human beings. Still, eventually I reckoned, this is even better, given I was born here. Why do I not try to make the country I was born in, a true place of peace? That was entirely possible. To make this country a real paradise, unlike the hell it actually is. The core^[see [Krugman](https://pr.princeton.edu/pictures/g-k/krugman/krugman-increasing_returns_1991.pdf)] of Africa and not the periphery it currently is. Over time, as I grew up though, this idealism slowly waned as I was confronted with the amount of quackery that is prevalent in the Republic of Mauritius, in all sectors, all wakes of life, all households, from the richest to the poorest. We kind of suck, even though I will not deny that there are a lot of very competent people in Mauritius. When compared to the world though, even you and me the competent ones, we undeniably suck. I say this very humbly of course. I may be intelligent in the Republic of Mauritius but to the world, I am most average. Still, the world is fairer out there than it is in here. Which can only mean it might be time for me to get out there to be able to make a name for myself without having to suck some politician's dick. I want to be my own person more than anything. You feel me?

Still, there remains this growing pit in my stomach. You are leaving your own behind, my mind screams at me. What will they do without you? You know, no one gives a single fuck about them. They cannot afford to. Of course, I would be leaving my family behind if I left. But my family will do just fine without me. You see, the real reason my mind screams at me and makes me feel guilty everytime I think of leaving this prison behind, is you the population of Mauritius, because I would be leaving you behind to rot in this hell by doing so. I would be letting these dumbasses take advantage of you. So, let me make things clear and keep it 100 with you. This is not a heroic endeavor. I want to be the head of state of the Republic of Mauritius, because I know that I can make this country reach advanced economy status before I die. At the same time, I know it is a pipe dream unless things drastically change. This anonymous website will allow for that change to be possible.^[This website creates a [new probability space](https://en.wikipedia.org/wiki/Probability_space) $(\Omega, \mathcal{F}, \mathcal{P})$, for our country as a whole. One where it will finally be possible for it, to gain true independence and become a real republic. That chance just increased from 0\% to > 0\% . As more and more people read it, that will trigger a set of events $\mathcal{F}$, which will dynamically update the original sample space $\Omega$ outcomes along with the new probabilities $\mathcal{P}$, associated with each of them after each new event $\mathcal{F}$ , one of which will be the probablity of the emergence of the Second Republic ($\omega \in \; \Omega$) which will be in the sample space. Meaning my aim is to bring $\mathcal{P}(\omega \; | \; B )$ as close to 1, as I possibly can, by getting more and more people here represented by $B$, to read this website. If you want to help create a better Mauritius. Share this page with a lot of Mauritians. ] I got the inspiration from reading the [original federalist and antifederalist papers.](https://billofrightsinstitute.org/would-you-have-been-a-federalist-or-an-anti-federalist)^[For the Federalist papers go [here](https://avalon.law.yale.edu/18th_century/fed01.asp). For the Anti-Federalist papers go [here](https://teachingamericanhistory.org/document/brutus-i/) and [here for the rest](https://teachingamericanhistory.org/search?results%5Bquery%5D=brutus&results%5BrefinementList%5D%5Btype.label%5D%5B0%5D=Documents)] It will most importantly ease my conscience because after this, I will not feel guilty anymore. This is me giving it my all to help my country.

If you can finally see just how much you got played for 56 years, maybe that anger can change things. The realisation that the source of all your suffering was the only thing you believed in your entire life, which is communalism and race voting could finally be the nail in the coffin that pushes you to accept that communalism voting has never ever benefited you, the general population. It benefitted a very small group of people for 56 years. Yes, these people are billionaires today. But they only are because they stole the rewards of your sweat and your parent's sweat for 56 long years. If you can accept reality as it is, then a new dawn will be upon us. A new chapter in the history of the Republic of Mauritius.

:::{.text-center}
Where together we will bid adieu, to the Monarchy of Mauritius forever and get true independence after 56 years and a real democracy.^[see the [proposed constitution](/constitution/preamble.html) for more information.]
:::
:::

