---
listing: 
  contents: posts # all Quarto docs in the `posts` directory will be included on your listing page
  type: default # or `default` or `table`; each type has its own set of yaml options to include
  fields: [author,date,title]
  sort: "date desc" # can also sort on more than one field
  categories: false # allows you to sort posts by assigned categories
format: 
  html:
    page-layout: full
---

:::{.box .bs-right}

# The Citizen Gazette
:::

:::{.box .bs-bottom .ji}
:::{.center}
## TO THE PEOPLE OF THE REPUBLIC OF MAURITIUS   
:::

You are being told that the coming election is the most important one since our independence but no one is bothering to tell you why. I think that this is a problem in our country which I personally find very disrespectful. Politics does not respect you enough to be real with you. Your future is in jeopardy, your children's future is in shambles and yet politics does not feel like the general population is entitled to know what is really going on in their own country. You are deemed too stupid to ever realise that you are being strung along on a wild goose chase that has no objective truth to it.

Unfortunately there is some truth to that given many could not care less about the objective reasons why the coming election is so important, because for many the drama of parliament, 'meetings' and memes on facebook where every political party will 'zette labou lor so camarad' will be more than enough to keep their stomach filled till the fateful day when we will all go to the polls. Nevertheless, Mauritius is different today, there are plenty of people of reason in our midst, and people who understand math, who are probably curious about the objective truth. At its core, the problem is the age old one which has always plagued the country for 56 years and has to do with competence. The casual observer of politics in Mauritius will often refer to that problem as the dynasty problem of Mauritius. The dynasty problem while very real is not well defined using the word dynasty because it is mostly used as a hyperbole, for its buzzworthy qualities. A better and much more accurate word is what in the United States we would call Nepotism Babies henceforth called nepo babies. Now, nepo babies exist everywhere, in all professions not just in politics, and in every country of the world. It stems from the fact that every parent will do whatever they can to set their child up for success so that they can further their own legacy and position in society. That is something every human being will always do. It is a human instinct. Can we really call it a problem then, if everybody in the world does it, making the only solution to it, being the annihilation of the human race itself? Is it not just human nature then? I tend to lean in the latter. You cannot do anything about this phenomenon. It is how human beings function.

Being a nepo baby does not automatically mean success, it gives you a leg up in life, but it does not guarantee success except in some cases, where the parent is deliberately creating that success for their child in the background. But even then it is not everlasting. What I am trying to tell you is that while a nepo baby is born with an advantage in the world, which is undeniably true, the continuity of their success depends solely on them. In Mauritius though as it is the case in many other small countries that is different because we lack the basic foundations of a proper democracy given our nepo babies have rigged the game. The economics of our country is nasty when you know of them. Our nepo babies have cornered the market, given how our constitution and laws have been set up. Historically this has only been possible because the average level of education was low. The truth is nothing is truly a free market in the Republic of Mauritius, be it politics or any industry. That is a blatant example of there being more than just nepo babies in Mauritius which is what the real threat is, as illustrated in this article [here](https://time.com/6322748/presidency-family-business-essay/) masterfully. It is their cooperation together as a group that can sometimes be to the detriment of an entire country when they corner it entirely, resulting in a phenomenon called despotism. 

The truth of the matter is that many politicians' careers should have ended a long time ago in a fair market that is working correctly. But they did not. The truth of the matter is that some conglomerates should have failed by now, but they have not, because they get free access to taxpayers' money at rates that would make anybody successful. On the flip side, it is also true that some conglomerates were forced into failure because the nepo babies of this country are in full control of it. We have to be intellectually honest. If you give me a loan of 1 billion rupees at 2\%. All I need to do is buy corporate debt at 7\% and I would basically be netting 5\% too. That is fifty million rupees net without doing anything. It does not take any genius to do that. Is it normal that some get this kind of opportunity while others never will? Is it normal for someone's cost of capital to be this heavily subsidised? No, it is not normal and you do not get that in a real free market. A real free market is efficient. You only get this phenomenon in a rigged market. A rigged market is inefficient. 

A rigged market has the interest of some few at heart, while an efficient market with minimal intervention to decrease inequality has the interest of an entire country at heart, by default. That is the beauty of capitalism. Its unfairness is a million times better than any socialist bullshit you could come up with in the very long run because it is so productive, that the little you will do to decrease inequality will ultimately do more in real terms. We pride ourselves as capitalists, but secretly we really are a communist country that disguises itself as a socialist one, if you understand economics. The setup is very CCP-like in Mauritius with an abundance of SOEs and a government that is a Kingmaker in the private sector and can destroy virtually any company. Which is why we are stuck as a country having barely made any progress for many years now. We need capitalism. We never really had it. But if this country is to truly progress, it needs cutthroat capitalism so that the most competent people can make this country successful in both the public and private sector. It needs efficiency. For that to happen, it needs more competition. Real competition. It needs to let bad businessmen go out of business and let the good ones become the richest in our country because these bad businessmen are choking the rest of the population everyday with their incompetence.

An election was very likely stolen in 2019. I cannot do anything about it, you cannot do anything about it, and if they do it again, no one will be able to do anything about it. The only thing I can do is tell you what I know. The economics of our country, so that you can understand why they even stole it in the first place. I am not going to tell you who to vote for, that is obviously your prerogative. I will show you the scientific truth of how the entire world works with simple macroeconomic laws. I hope that it will help you make the best choice for the future of our country because our country has none currently. Despotism hath taken your future.

---**YUUKI**


:::

:::{.center .box .bs-right}
# THE CONCERNED CITIZEN
:::
