---
title: "An ode to our oppressors"
cap-location: bottom
subtitle : "This paper uses common sense and logic to destroy what can only be referred in Mauritius as couyonne lepep-ism disguised as socialism"
author: "Yuuki"
date: "08/11/2024"
---

## What is a word ?

Have you ever wondered what a word really is? Why do they exist? What do you think came first? The words that you write every day or the human being that wrote them? Did the words and alphabets of each language exist 500 million years ago? The answer to that is of course a big old **NO**. We human beings invented the languages we use. One might then ask, well how do we know that a computer ought to be called a computer, or that the sun ought to be called the sun? Why not call it Bob, I would fancy that. Let's all call the sun Bob from now on. Why do we not do it? You very well could, nobody is stopping you but most people would not understand you because their brain would not map Bob $\longrightarrow$ Sun. They would map Bob $\longrightarrow$ name of a person. You ever look at a color? Your brain will tell you the color you are looking at although there is no rationale for why red maps to what we perceive as red.^[Yes, I know that colors are just EM waves being processed by the brain, we are walking here not running]

So why does this happen? It happens because your brain is trained like a lab rat to learn these mappings through the [art of language learning, vocabulary learning, and sentence writing.](https://www.youtube.com/watch?v=J_9X8PVlfBE) We have developed languages with words, then with the alphabet to be able to convey meaning to 'stuff' that exists subjectively and objectively. We tend to follow those languages to a tee. That is after all why they are effective tools of communication in the first place. First inside your house to learn the basics but then you are sent to school, all around the world, so that other maps may be accessed and learned through all the subjects that we have in school. The very nature of this subjectivity that each brain is privy to is why lots of countries love indoctrination and why the social sciences are so nonlinear. Human behavior is filled with all kinds of nonsense that determines said behavior which is why it is quasi-impossible to predict, although it is nevertheless deterministic. Education is therefore a double-edged sword because education and indoctrination are two sides of the same coin. You can provide your people with reliable information about the entire world by sharing all the best available knowledge that mankind has at its disposal through the process called teaching in schools, colleges and universities or you can use it to your advantage to raise a lot of sheep by altering things here and there. In Mauritius, a simple example is the fact that there is a clash of words today among the older population and the younger population. That is because words like Democracy, Fairness and Merit mean different things to both groups. So a good objective definition of what a word is that it is.

::: {.callout-note}
## Definition
A word is a placeholder for our brain which maps its perceptions of the world to it so that it can be used as a tool of effective communication. Words can be used to convey subjective and objective perceptions.
:::


Ah so salty! Ah so sweet! Have you ever thought if there is such a thing as salty and sweet **independent of us as human beings?**. A cat for example, [does not know what sweet is](https://www.npr.org/2005/07/25/4766556/cats-cant-taste-sweetness-study-finds). So the answer is that those are both subjective and objective things. Living things have genes (objective part) that allow them to process what we call sweet and salty (subjective part) although in some if their tastebud receptors are not working, then they will not be able to perceive what sweet and salty is. That is an objective statement. Objective statements are generally based on logic and science.

## What is socialism ?

Did you really need the word socialism to be invented and emerge in the world of human beings to realise that there is an inherent need for fairness in society because free markets although best left to their own devices, do result in a number of desirable and undesirable outcomes? The primary of which among the undesirable ones is inequality and monopolies resulting from profit maximisation, scale and first mover advantages in a market. So, you need government intervention in any fair society. How much is really the question and where populism can sneak in disguised as socialism? Socialism is just capitalism plus the least amount government of intervention required to make society fair. That is the correct and only objective definition of what socialism is. Socialism is always the way to go when you are willing to interpret it in this objective definition. But that is not the definition that is used here in Mauritius.

Before we discuss that, let us understand why socialism is not a choice today but rather the gold standard. John Maynard Keynes in his [General Theory of Employment, Interest and Money](https://en.wikipedia.org/wiki/The_General_Theory_of_Employment,_Interest_and_Money) changed the way economics is done forever because he elegantly showed a very simple albeit very pertinent point. That markets can stay in disequilibrium for very long periods of time in a downturn because markets stop clearing meaning that there is a tendency for Prices to not readjust very well in an economic downturn to make demand equal supply because of laws, unions or human expectations and conventions that tend to put inertia on the price of labor and goods and services causing them to become sticky. Keynes suggested how government intervention can help by applying "force" to jolt free markets which left to their own devices would take much much longer to clear on their own (Get the right price adjustments to happen so demand equal supply). That force was fiscal stimulus and programs that put a backstop on aggregate demand like unemployment insurance or programs that decreased inequality that provided a consistent flow of fiscal stimulus so as to always keep the economy at a fair equilibrium with programs like food stamps. Add to that free education, anti-trust laws, general competition laws, regulations for food, health & safety and universal healthcare as well as some minor other things I may have missed and you have most modern economies in the world except the US I guess.

## The Couyonne Lepep-ism

Objectively the couyonne lepep-ism is not something that is only prevalent in Mauritius. It is a fan favorite among all governments in the world. Just like the UK washes its sins in India by rewriting history in its A-Level curriculum, or the USA washes its sins of the genocide it committed early in its manifest destiny era which was a major inspiration for Germany and its subsequent horrors, which was only following America's tradition of eugenics and mass massacre, to begin with. The thing to keep in mind is that nothing is truly as it is told when it concerns history. Human beings have biases and that will affect how human history is depicted by governments based on their self-interests. A tyrant will be a hero if self-interest calls for such a thing to be the case. The world is a horrible place, but it is that which makes the momentary peace we can secure every now and then that much more enjoyable. If you want to have an objective opinion of the world, you can only have one by understanding the science that rules the world. Science will not lie just as Human Nature will not lie. Why is capitalism so successful? Because capitalism is the only objective description that a society can truly have. Any other is subjective. All societies run on greed which is dominated by [gilded ages](https://www.youtube.com/watch?v=Spgdy3HkcSs), and then are followed by small periods of great equality before going back to a rinse and repeat. Man is flawed. There is no good or bad. There is only good and bad. Karl Marx's ideology of communism is not something that actually exists objectively, it is fluff used by many greedy people throughout history to get control of factors of production and to create a defacto Monarchical system in their countries. We call them dynasties in Mauritius but they exist in a lot of other places across the world. Objectively that is what communism has been if you study it. It has never been what it has claimed to be. This is what the older politicians in our country do not get. Science has you beat. 

You are not different. You are not that one political party that is not a [political machine.](https://en.wikipedia.org/wiki/Political_machine) Because that is what all political parties are. That is the science. Human beings if nothing else will always excel at being human beings. That is the problem in Mauritius. Acting holier than thou with the younger generation, when all of us know that what is required in Mauritius is not the perfect politician but just for the goddamn laws to work. We know you stole money, all of us know you stole money. We know we are not different and that we could have done it too for all we know if we were in your shoes. That is not what bothers us. What bothers us is that you did not serve that prison time you should have served for all those crimes. What bothers us is the the rule of law fumbling time and time and time again and being unable to secure even an ounce of justice. There are an incalculable amount of people in Mauritius doing obstruction of justice and aiding and abetting every day by not investigating anything that is sent to them and getting close to a million rupees per month for it. Do you think all the young people in this country do not know that? How dumb do you think we are? Now, one will perhaps ask, well is the world communist then? The answer is if they meet two conditions that we have here then yes. Number one is any country with a big government, which just has way too much arbitrary human bias that rules them. Bigger government automatically equal bigger political machines and a bigger amount of savings that is stolen. Government can only be inefficient, the bigger it gets because we are all greedy. Number two is that the rule of law stops working completely. Plenty of countries fulfill those two conditions today. We have been fulfilling it for a lot of years. When that happens, you are done, you can no longer pretend to be a socialist economy. You are a communist country. When laws stop working, it's no longer about being a welfare state, it's about being a mafia state and just expropriating all the savings of a country in a typical political machine fashion.

The biggest problem that Mauritius faces today is the hoarding of its capital. Not all people are allowed to shine in Mauritius. You could be extremely incompetent and still shine due to the fact that you are part of the Monarch of Mauritius, by getting money continuously thrown at you. Public tax money. That is inefficient, because these people did not generate new savings in the end. These people just ate billions of savings of the country and gave nothing in return and is still asking for more and is being given more. We are letting incompetence shine rather than competence. That is how we got here. You see, the capital-output ratio and the capital-labor ratio are low in Mauritius, which means that, the price of capital is consequently high and real wages are low, but take a country like China for example. Even though it is a communist country, it does not matter, because its KY ratio is so high, and the price of capital is cheap, meaning there are relatively low barriers to entry finance-wise. Likewise, any other advanced economy in Europe that has a big government will have the same characteristics. So there is a lot more competition in those countries. We want that to happen in Mauritius. But it has not happened. The one player that was doing it which was BAI was killed. Facts remain facts, his company was destroyed because they did not agree with his way of running things. He was pro-competition which the rest of this country is heavily against. Which is why, they pulled out their capital by working together and conspiring to take the man down. The man did not die though, that is the part most do not understand. There was no Ponzi of any kind. He had more capital than they could have imagined, their plan failed pathetically. So, they panicked and revoked the banking licence of this man, with the central bank failing its fiduciary duty to the components of the financial system (basically you the people) of the Republic of Mauritius which is to act as a lender of last resort so that your money stays safe. This is what should have happened, but even then with the central bank pathetically failing its duties, the capital was found but the money was rejected and the banking licence was revoked. In the end, they retorted by bullying him and making him go through hell when their conspiracy failed by lying and doing what they did best - inventing a story about a Ponzi scheme to forcefully crush him. 

These people are not your friend, you need to realise this. If you were to become that man tomorrow, your fate would not be different if you were not part of this incest club of Mauritius. Screaming democracy! democracy! does not make a country democratic. We need free capital markets which are looking to make the best buck not a bunch of insecure wankers who have to make your life miserable just so they can maintain their lifestyles. We need trillions of dollars of capital to make this country democratic over the next 50 years. We can have it if you start choosing competent people. We have to privatize most state-owned companies to bring huge amounts of foreign capital in. For example, the CEB has to be privatized, ideally giving the buy to a US company that has good relations with a refiner, who hopefully is willing to invest big bucks. We are talking billions here, of dollars yes. The plan has to be to refine and produce lots of stuff here for further processing, export and domestic (port) consumption. We can do other stuff that comes with entering this value chain and work our way up to electronics step by step. Madagascar lacks electricity coverage. We can export electricity to Madagascar and it would be a win-win for both of us. We can build an interconnector to Reunion too to better manage our electricity needs and build one to Rodrigues, where we can build solar farms or even a small modular nuclear reactor (they are climate friendly). We'll have economies of scale, and cost savings and that will be our point of entry into capital-intensive industrial manufacturing. The biggest factor inputs that we can have control over and compete in are electricity prices, if we can do it cheap enough, and transport subsidies. Population growth is not going to magically come overnight. But those two things, I just mentioned, would be our win condition in the short-medium term. This is me being very serious. This is not a choice we can avoid. We either stay stuck in limbo or you do capital intensive stuff and become a developped economy. We need economies of scale, nothing else will cut it. Our output per worker is not 11 or 12k, it is around 8.8k at best. That is the peak you will get stuck at doing labour intensive industries without generous trade deals. It's not easy but you have me if you want me of course. Doing all of this will only be profitable for you the people of the Republic of Mauritius in the long run. Your real wages across the board are what will go up in this scenario. These kinds of things will allow us to become an advanced economy and you to have any dream you wish. I will open the country up completely to foreign capital so there is competition. It is very important for Mauritius to build its relations with the US in other sectors, other than financial services so that we may actually become America's favorite place to set up ANY business in Africa rather than SA. You do that by building relationships with lots of US businesses. But this is what our country dislikes. Competitors.

Do you even realise what reliable electricity access would do for Madagascar? People in this country always moan that we must do agriculture, but why should we when there is a country that has a thousand times our arable land? Why should we do agriculture when they could do it and we could do the better thing (the core activity rather than the periphery activity) and just buy agriculture from them with our export earnings of electricity by both being better off with free trade? My vision for Mauritius is not farfetched, we can become the core of Africa. We can have a country where anybody can become president, where anybody can become the richest, where everybody has a bill of rights protecting them, and where we can have the Mauritian dream exist for everyone after 56 long years. This country can become more than just a 'fake paradise', it can become the absolute best place to live in the entire world. This country can belong equally to all citizens. We can become the industrialised economy of this part of the world. All of this is very doable and all you need to do is let the competent come in and do what is best for our country. I do not mean to be disrespectful, but a lot of the politicians in this country are not educated enough. They cannot do this for you. Goodwill does not bring dollars back to our country so you can have a prosperous life. Goodwill and good faith politicians ironically will always need to exploit you. All of them are merely reactionaries to the current regime's lies. They do not understand literally anything of what is truly going on in this country. All their ammo is aimed at corruption, promising to throw more money at you than the current regime or political theatrics to get people emotional so they can get on their ballot paper. 

Politics in our country has been pathetic for more than twenty years now besides the Second Republic plan which could have worked had they proposed something as concrete as what I did [here](/constitution/preamble.html). Besides that politics has always been this silly dance involving theatrics, and a dumb game of inbreeding that is practiced with the complicity of the private sector, which is true of most places to be fair. The US does the same thing, but the US has a private sector that keeps it growth steady. We do not. We have no growth. These people are literally killing everybody today with their selfishness and greed. And yet I cannot do anything about it. The indoctrination and lack of education in this country has bested me. Even if there were 60 of me, I would still fail to change this country. I'm stuck. You are stuck. Nevertheless, I am here, if this country needs me. The real reason there has never been any real change for 56 years, is because all political parties are aware of just how much their indoctrination has worked and is still paying dividends. Communalism is the only thing left that is exceedingly productive, it works very well. So this is really all I can do for you, and even for me to be honest. To confront this country and all its political parties with the disgusting truth that hangs over it. Force them to rise up to the actual problem at hand, to have to at least be better. If this blog gets popular enough, they will not have any other choice but at minimum to be reactionaries again and give you the Second Republic but you have to also hold them to this standard as a country if you want better rights and a real prosperous future. There are a good 2 and a half months left before elections and before inflation kills the regime's chances. Currently, we live in a prison. Where for 10 years you have been lied to about the economic performance of your own country. I am not a big fan of the Labour party but atleast they did not lie in the 1980s and use repression and terror to hold on to power. This mentality that the regime in power has today, is a colonial mentality of looking down on the people of this country. Exploiting them at any cost. Whatever it takes. I will say it again these people are not your friend. These people are our modern day colonizers we must get rid of imperatively.

And yet suddenly these very people are the ones who care most about you just before elections. That is a huge red flag. You care about my well-being more than even myself these days, what the hell is wrong with you? Are you perhaps, doing all of this with ulterior motives? Indeed, that is where things take a dark turn. In that, it is not really about helping, what it is about rather is the story that is being weaved. That they are helping us. Just like almost every youtube video out there. It's about the illusion that they are saving the day. Elections are closing in. You are now officially the love of your politician's life again for the next few months. But what about where this government could have objectively helped you though? By passing a Freedom of Information Act, for example, you could have kept SOEs accountable. It confuses me. Why do you care so much about me and yet care so little about me being able to hold you accountable for your actions? Tell me. Why are so hot and cold? Why is it that we still have National patent exhaustion when you could make my life so much easier by allowing those parallel imports? Why did you intentionally choose to make me buy medicines at 10x their cost and then act sly and coy with me by giving me a cost of living adjustment that is worthless? Is it because you care about me or do you just want to get on my ballot paper? Which is it, my love? Why do you sell this country's state land for chump change to yourself and then resell it for a quick buck my love? Is that because you care about me too? Why are you not paying my overtime then love? Are you that big a narcissist?

Are you perhaps cheating on me love with the private sector? Are you having an affair with them for 10 years now but pretending to be in love with me at the very end to use me yet again? Did you honestly think that I was not aware of it? That I am like my parents, that I run on communalism and fake promises? Be honest with me love, you secretly look down on me, like you looked down on my parents for 56 years, do you not? Do you think you are fooling us like you fooled our parents? I mean how else could you so proudly tell me you are increasing my wages when we both know objectively all you are giving me is more misery and more inflation because there is nothing to give? How else could you tell me that even though life is only getting harder, I am supposedly living a good life? Your gaslighting is getting out of control love. You are suffocating me. I cannot even look at you anymore. Everything is gone is it not? Spent in your little love tryst with your cronies, relatives and other mistresses for the past 10 years. You have ruined my future and the future of this country. We have endured and endured for ten years and watched as you disrespected us every day. This is not working out anymore. Stop handing out useless gifts. It is time for the abuse to stop. We need to be free of you. We cannot breathe anymore.

You, our oppressors have single-handedly destroyed the dreams of 1.4 million people. It is time for us to break up. We have no use for you and your love of this country being filled with slaves you can exploit. We have no use for your love of sharing your rent (profits) with the political class so that together you can rule this country with communalism by dividing it. Can you do automobile manufacturing? Can you do semiconductor manufacturing? Can you do electronics manufacturing? Can you do oil refining? Then I have no need for you. You are not essential to the Second Republic. This country will not be a prison anymore. This country will become the core of Africa and its most prosperous nation. Stand in the way of that at your own peril. So how about it people of the Republic of Mauritius? Do you want your child to be able to have the dream of being the President of this country?


</br>

</br>



::: {.callout-important}
## P.S
On another note, inflation expectations have shot up even more given COL adjustments have gone from 1500-2000 for this year to 4925 which is more than 10x the cost of living adjustment of 2020 which is starting to become scary. Its almost 17x. So cause and effect wise, this increased cost of labor will be passed on in the goods and services fully because productivity naiba - increasing the RER which means the potential output (supply side) is going to go down which means the lower bound of the unemployment curve has to increase substantially. Will we contract again? We very likely will but it also means elections have to be this year, because inflation is getting out of control and you cannot raise the key rate, that would be a death sentence. By mid september the population should be showered with central bank money, and parliament should be dissolved before 9 Oct to go for elections quickly the next month before inflation becomes too big a problem. 
:::


