
---
title: "God's Plan"
cap-location: top
subtitle : "This paper espouses the view that everything is determined by god and that our country could not accommodate a real democracy for the past 56 years because it wasn't ready. But that period is over, through the grace of God, because education has crossed the required threshold now. After 56 long years, our Kingdom will finally get to be a Republic that belongs equally to each citizen. Where everybody will finally have defacto access to the same rights and the same opportunities."
author: "Yuuki"
date: "03/12/2024"
---

## A deterministic world governed entirely by god


That the world that we live in can be understood, is the premise I stood on in writing all of this to you. That is why I was able to explain to you how exactly the Kingdom of Mauritius went bankrupt but you must also understand the power of knowledge, for I did not only explain to you how the Republic of Mauritius went bankrupt. What I have explained to you is the fate of all countries with a low capital-output ratio. The fate of such a country is that it tends to win its race to zero growth and once that happens it does not generate enough real savings anymore, and so it will start to fail to converge to become an advanced economy because of [Debasement, Debasement, Debasement, Debasement, Debasement, Debasement, Debasement.](https://www.youtube.com/watch?v=hMLcKtVwF-A) It is then a rinse and repeat basically until the complete collapse of the country which is where we are at after 56 years of "independence". That is kind of the national anthem of the dumbducks of this world. All around the world, dumbducks use a single thing to fool you, Race with a sprinkle of communalism. Fear mongering while keeping you stupid. Do you realise that for 56 years, your parents' sweat has been their get out of jail free card? They dumped their financial troubles on you without you realising it while cajoling you with communalism by giving you a tiny piece of bread to enjoy on the street while they sipped wine in their ivory towers. The bank was never their banker, it was always you and your sweat that was stored in the bank.  That is the true face of communalism for you. That is the deterministic outcome that you will end with as long as you have a team of dumbducks that are in control of your country. Thats it. If by now, you are still a believer of the politician who just comes in and screams 'malbar mari', 'lascar mari', or 'creol mari' and that is enough to win your vote despite what I have shown you. That is most of them by the way. Then fuck me for believing in my country, I was wrong. I have done all that I could, so I will simply see myself out, we lost given this is the case $\mathcal{P}(\omega \; | \; B )=0$. Hell on earth is all our island will ever be.

But if you have decided to let go of this parasitic thing that divides us all that is called communalism and if you are finally ready to embrace the power of science and knowledge, then we are in the case $\mathcal{P}(\omega \; | \; B )= 1$. Then we are going to do great things together you and me, and make this country the core of Africa. As you know, the power of science comes from the fact that by explaining to you what happened to the Republic of Mauritius, I simultaneously explained to you what has happened everywhere else in the world with a low KY ratio, like in Lebanon, Bangladesh, Turkey, Sri-Lanka, Egypt, Argentina, Nigeria (The entirety of Africa actually). You should learn to appreciate the fact that science is not at odds with god, and embrace science to be able to understand nature. All science does is omit the definition of god to focus on understanding nature, solely without any distraction of the religious kind. But to say that, all that is happening is being determined by god itself is not something science could tell you is wrong. Plenty of scientists believe that. I believe that. Sir Isaac Newton believed that and he is the most intelligent human being to have ever existed. So you are in good company. To say that God determined that all the countries that I have mentioned above would remain in the dark and collapse without their people ever truly finding out the objective reasons as succinctly and as clearly as you have is a fact.

Now, I do not know why things were destined to happen this way. I am just as much clueless as you. I am not more special than you or anything. I am just some guy fighting for his country's freedom and future. I am fighting for my future and my kid's future. What I can do though, is give you my opinion on the fact that for some reason, We the people of the Kingdom of Mauritius have been given an incredible blessing after 56 years of oppression. I know it can be hard to digest it this way when your retirement has been ruined, your insurance money has been ruined by inflation, your investments have been ruined by inflation, your wages have been ruined by inflation, your entire life has been ruined by inflation. I get it, trust me I get it, how hard life is currently. The inflation is the same for me too. But we went through the same thing in the 1980s, only we did nothing about it then. Not to sound arrogant or anything of the sort, but clearly nobody gives truly cares about us. It was this easy to win the coming general elections. Did you see anybody do what I just did? I know for a fact that I am not a smart guy. I'm relatively dumb. Anybody could have done this and yet this is the problem with our 'experience' heavy politicians. That is just the truth. What the hell is the politics of this country doing exactly for you right now? Creating meme accounts on facebook 'pou jete labou lor zot l'adversaire'. Using drug money that killed this country's children to give you gifts? Giving you food baskets after having stolen your future? Going on tv using props as dressing to appear 'indian' or 'muslim' or 'creol'. How insincere must you be to use a prop? How illegitimate you must feel inside? Is that all you have? Do you not see how low the level is with communalism? Prend toi pou bobok trop couyon ki pa merite konne la veriter. Prend toi pou bobok ki alerment telment couyon ki lakoz mone met un linge religieux to siposer croir mo sympathise ar toi. To p trouv kit respect kitpar ladans? Sa pa arage toi gogot? 56 bananer in aller coumsa. If I had been born in the inner circle of politics of this country, I never would have written this and risked destroying the very privilege I would have depended entirely on and thoroughly enjoyed. I am risking my life here. So you see, there is no other way for me to look at this, other than this has all been god's plan to liberate our country. Many people will probably wonder what I believe in, religiously. I told you at the very beginning that I believe in the absence of free will, that we are all controlled by god and there is a passage in the Mahabharata where such a philosophy is beautifully exposed.

::: {.callout-note}
## Mahabharata - Book 3, Varna Parva, Chapter CLXXXVIII 

I am Narayana, the Source of all things, the Eternal, the Unchangeable. I am the Creator of all things, and the Destroyer also of all. I am Vishnu, I am Brahma and I am Shankara, the chief of the gods. I am king Vaisravana, and I am Yama, the lord of the deceased spirits. I am Siva, I am Soma, and I am Kasyapa the lord of the created things. And, O best of regenerate ones, I am he called Dhatri, and he also that is called Vidhatri, and I am Sacrifice embodied. Fire is my mouth, the earth my feet, and the Sun and the Moon are my eyes; the Heaven is the crown of my head, the firmament and the cardinal points are my ears; the waters are born of my sweat. Space with the cardinal points are my body, and the Air is my mind...

...And, O Brahmana, whatever is obtained by men by the practice of truth, charity, ascetic austerities, and peace and harmlessness towards all creatures, and such other handsome deeds, is obtained because of my arrangements. Governed by my ordinance, men wander within my body, their senses overwhelmed by me. They move not according to their will but as they are moved by me.
:::

However, that can be something that is considered taboo to accept, because to accept it is to relinquish the responsibility of the human being, which is why we might never accept that everything is moving out of its own accord. Some will come up with "I did not do this crime, god made me do it". That view while technically correct is misplaced because such people do not embrace or understand what the absence of free will means. They are getting philosophical rather, about the ramifications of a world where nobody was ever in control of their actions, but nature has already made provisions for it. God has already made provisions for it, because if there is no free will then only god could have invented the rule of law, as well as all the various religions and everything else in the Universe which includes the illusion of free will. And as crazy as it might seem, only god truly judges people then through the judges he created and the rule of law that he created. When criminals get away with things, it is god's will. What do you want me to tell you? That is the world we live in if it is to have a god. The most important point though that you are missing in all of this, is that the absence of free will means that things can be explained. Human behavior can be explained scientifically. Nature can be explained, and the motion of planets can be explained. You do not do anything randomly and that is exactly what the absence of free will is all about. You are governed by your brain and the instructions if you will in it or the latest version of the software called 'You', that your brain uses at all times. On a simpler note what I believe as god can be simplified as the [Universal Form](https://en.wikipedia.org/wiki/Pantheism).^[Krishna's Vishwaroopa] To me the meaning of moksha is to let go of everything and acknowledge that 'tou dans lamain bodier. mo pa parfait, mo role, li ekip moi au mieux pou mo faire moins pecher ki mo capav permet moi fer dans sa lavi la'.

## The principle of least sins

Now, before we move on, using simpler and more common examples of life in general, I would like to showcase to you how powerful the absence of free-will can be to understand the world we live in. Like I have said numerous times in these papers, one can only be as kind as they are competent. That is a way of thinking about nature where you acknowledge the absence of free will. There can be no morality if there is no competition because people are not free by design. Competition is the most important constant that morality depends on in the world. If giving you ultra processed foods comes at no cost to the bottom line of companies. Companies are just going to keep killing you. You do not believe me? Look at what is happening with climate change. We need that damn carbon tax. Just as a human being cannot love everybody (sorry, politician-kun) because nothing bad would happen in the world then. Contrary to popular belief, anything is not actually possible in real life. That is just how things are, there are probabilities rather, to various events that can happen at all times based on who I am and my patterns of behavior, my habits, my likes, my dislikes and my competence. These are all important logical things that are very easy to come to in the absence of free will because even though it is not provable empirically, such an assumption nevertheless keeps on delivering a more robust understanding of nature to us every time we use it. It is a simplifying assumption in trying to understand the world without all its chaos. You can continue to believe that you are freely determining your actions and only use this simplifying assumption to understand the world that you live in. That is fine as well because it does not matter in the end. What must happen will happen.

For example, your previous leaders could not impose the death penalty on the hard drugs (heroin, cocaine, synthethic, meth, fentanyl). But I do not need an income stream that kills this country's children, I can afford to just invest my money in US equities and make enough money that way just fine because I know how to do it. Do you get it? I'll impose it no problem by law on these hard drugs, and decriminalise cannabis, so those kids dealing can be reskilled and transition into legal work and have a real future. It was that easy, for 56 years. All you needed to do was put someone actually competent and responsible up there, who did not need that crutch. Someone who could give a damn. Similarly, abortion rights for example, is a topic in Mauritius that does not get enough attention. Do you know why? Because it does not matter for rich enough people, although abortion is illegal, they have it very easily without a hitch. But what about women who are not as rich? They have to risk their actual life, and immense emotional trauma. Have you ever aborted a baby? I know people who have and it is not easy to do it alone. It is not easy to dump that child (no I will not write the other word). If you do not know that then you would not understand how dangerous it is and how devastating it can be. [But your right to privacy will be protected by section 11 in the Rights of the People in the Second Republic](/constitution/Rights.html) [and districts cannot take it away because of section 4 of Decentralization](/constitution/Decentralization.html). Every women will get to choose, in the Second Republic. I believe the choice should be given to every women out there, and whatever they choose is none of the state's business.

Especially because in cases of sexual assaults, when the body of a human being undergoes freezing, be it a woman or man, that is not the woman or man, not trying to get up and leave, there is no get up and leave in practice, there is the brain and its chemical response at that moment, which you are absolutely not in control of and your body's response controlled by those chemicals is to be forced into a freezing state to survive by appearing the least harmful possible. You cannot understand all of that without our simplifying assumption though. That the body acts as if it were dead and so does not resist anything at all. You would speculate all kinds of useless rubbish to be honest with you. Psychologically, the aftermath, the chaos, can be absolute torture to a woman when she goes through this again in her mind, because she will torment herself, as to why she did not leave. People will gossip about her if they learn of the incident, whispering that, that is what she was looking for, so she will question her sanity, will fall into a depressive episode, need to start heavily medicating herself, and eventually, she might even attempt to kill herself from her guilt eating her insides every day as she suffocates more and more from being unable to let go and move on from the fact that her body did what it needed to do to survive. To live another day because that is how the body interprets sexual assaults. As if it is going to die. My point to you in all of this, is to embrace that life can be understood and explained. Because it is how you level up. Honesty with yourself is the only road that leads to not repeating the same mistakes over and over again. People tend to think the social world is clouded in mystery because it is filled with lies, but it is not a mystery. It has objectivity too. Like our country's economic status. All lies on paper, but with objectivity, you get the truth. Now, no one out there is perfect. We are all incredibly flawed and can only grow by understanding the world more and more as it is. Not as you wish it could be or should be.

You might be wondering by now, so are we not going to appeal the heavens? Obviously not while I am around, I will never tolerate that kind of meaningless violence on my watch. But you must understand that, this is not the case at all for our King. The reason why our country has fully transitioned to a Kingdom is correlated one hundred percent to the fact that we have not had much of any GDP growth for like 10 years now. That is the cause of everything that you are living into today. The standard of living has completely collapsed. The repression of information, the repression by the police, the torture by the police that goes unpunished, the increased drug addicts around the island, increased accidents, increase in infections and deaths from diseases, the decrease in education standards, the increase in stillbirths, the increase in the malnutrition of kids, the increase of botched operations and health malpractices every day, the lack of medicine in hospitals and the increasingly less clean island we have today. Everything will get worse when economic growth disappears. That is just cause and effect. How could he establish law and order when he himself has been lying to you for ten years now? He cannot do anything about anything, because he is not competent enough. His hands are tied, when the PC takes your money and buys cars, or god forbid anything else. When any of his men abuses a citizen, when they do unspeakable things to innocent citizens, when they abuse their power to intimidate innocent citizens. Your King cannot care about you nor can anybody else in the Republic of Mauritius because his own insecurities about the truth ever being known will get the best of him. The same is true of all dumbducks.

They cannot be moral. Your parents have been constantly electing people who cannot in any way care about their well-being for 56 years, they screwed themselves, over and over and over again. Why the hell would they do such a thing? Why would they screw themselves over for 56 years? They could only ever have done that because they are not doing anything. They did not do anything, because they are not in control of their own actions. You have to be able to see that what ruled their behaviors was their carefully setup environment (the indoctrination) that they went through. The communalism they went through. It is not your fault or your parent's fault. Give yourselves a break. You have all been living in a prison, for 56 years, and I do not say this lightly. That is not a hyperbole for me. In any case your parents are not the villain of this story. All of these behaviors were governed by the education your 'ruler' allowed them to have, over the years. In Mauritius it was to keep your parents stupid and uneducated so that they would not see, that phonies were in charge. Dumbducks are the villains, make no mistake. 

The only real risk that remains now, at least to me is the behavior of political parties. If you remember at the start of all of this, I told you that all the politics in our Kingdom can be summed up as closed-circle family inbreeding. I was not wrong, given what has recently transpired in July, but we already knew these things. You already knew them. As we know, the entire country knows who killed who. These things are not coincidences. For an entire country to know who killed who and yet for justice to not have been served. These are carefully orchestrated things in the shadows by people holding guns to other people's heads metaphorically. You have to understand our country today is the far west basically, because it has not had economic growth for so long. Anything goes because there is no questioning the authority of some people in the police. Your King if shit hits the fan has only the police to use as a shield. As human bodies, he can throw at the population. That is a fact and why law and order is nonexistent. That is irrefutable proof that the law does not work in our country, anymore. 

How the hell can a country, accept a meaningless statement that a man gave a husband money for the employment of his wife and get away with it, with the benefit of the doubt? That is the weakest defense to have transpired in a court of law, in human history. [How is it that Danish prosecutors have already found BWSC guilty and nothing has even started here?](https://lexpress.mu/s/corrupteurs-sans-corrompus-536330). This can only happen when these are orchestrated things. Like invisible forces in the shadows, cleared the court's schedule so that they could move very quickly because if it had dragged on for let's just say 3-4 months, then the media would have discussed in detail this ridiculous defense that won and the population's eyebrows would have raised. And do not dare think, it was unappealable, it appears your King already holds our PPD by the balls.^[The biggest bane of the Kingdom of Mauritius, is that most people have dabbled in crimes because it has historically been a riskless endeavor for 56 years, but your King was smart, he held these crimes over these people's head rather than prosecuting them as leverage, so they will have to jump if he says jump] Your Kingdom has become a complete joke after 56 years. So let me clear again. We will never ever appeal the heavens, because as a general principle, we will always walk the path of least sins, while they walk the path of maximum sins, **HOWEVER** we will respond in kind if our King does not count those ballots on the same day when polls close. Pull off any shit, and you will get a taste of the wrath of this country for those last ten years of suffering. To me though it is weird, why someone would destroy their father's legacy just for their son to get a pension. The risk-reward does not match at all. To get him off a criminal case? He could have done that anyway by winning the general elections because the laws bend to our dumbducks. Nah he knows something else. He has privileged information. That our King will act like one and steal again perhaps? I mean if he has the touper to print money again in secret, what could be off limits to our King? Nothing. Too bad though, God has decided otherwise. There is no winning. Our King will lose and a Republic for all citizens will rise.

## The Grace of God

Now, you might be worried given our King is a well known master manipulator. What if he requests the assistance of India with a pitiful excuse, to oppress us. India will not get into a country matter nor support one person when a whole country is against him. My Bharat, your Bharat, the Bharat we all know will neither support nor condone slavery. They will remain impartial and let general elections happen as the greatest democracy in the world. Bharat will do what is best for Bharat. Remain impartial. So, No India, No USA, No France, No UK, No nobody. This is between us the people of the Kingdom of Mauritius, our King and his dumbducks and the polls of the general election. We are going to do great things with India, America, Europe, Asia and everyone else who wants good relations with our country in the future. My responsibility hereon is to do what is best for my population. I could not care less about what is happening anywhere else, nor how a country does what it does. My responsibility is to make your lives better. One can only wonder though, why now? Why did god give us this opportunity now? Why not fifty-six years ago? Why not twenty years from now?

That is anybody's guess. I wish to be clear that you should not take my opinions on destiny as gospel. They are my point of view and are a logical interpretation based on my understanding of the world. Just because I am being logical does not mean however that this is the answer. Commenting on destiny is a philosophical exercise. There is no right answer, technically. I would encourage you thus, to disagree and have other opinions on why we ultimately got this chance from god. Have your own interpretation, that is much healthier. I believe that it was impossible for us to become a democracy before today, because nobody wanted one. You think everybody has always wanted democracy, but that is not true in my own personal opinion, no one actually wanted a real democracy for 56 years. We wanted communalism. Communalism has not stuck around because of our politicians. It cannot be just the indoctrination that made it a fan favorite. It was its objective usefulness to most people. It stuck around for 56 years because it was the best system for the people of the Republic of Mauritius back then. There was no one with much education back in the day compared to today. We did not want competence as the metric that jobs use, because nobody had qualifications, degrees, or doctorate. But the ambition was still here. We wanted communalism to be able to get ahead in life.

You the young people of this country, who were repeatedly told that your degree will let you get ahead in life feel betrayed. You see, back in the day, people knew that communalism would allow them to get ahead in life. They had ambitions and they did not care that communalism is a vicious system given that it is only ever at the expense of minorities, so the majority back then of which almost no one had a good education, loved it. The probabilities of what they could achieve were much higher with communalism. It increased exponentially. That is infact the biggest problem today given our economy has no more economic growth and opportunities have become much more scarce. This fact that it still is the better choice, you get me? Coller Lafiche is still 10000x more prosperous than getting a degree. That has not changed yet, and that is what this country's young people are extremely mad about. They were lied to for all these years, by this country's dumbducks, who lied to their face about getting a degree to be able to get ahead in life. They did not. They got behind, they lack experience because they wasted so much time toiling in school and must today work for chump change because the politics of this country does not give a damn about them at all. They are all slaves of the system today and they want justice and fairness. I am going to give it to them. The road ahead is extremely hard because the worst is yet to come in our soon to be Republic. We must pass the darkest hour first, by responsibly dealing with everything this government has done and work on re-establishing the people's future to then be able to go into a new dawn and a new future, where our aim will be to become the core of Africa.

The path ahead is not easy, because we will inevitably need to ask for help in the future, the current situation is much worse than that of the 1980s because of the amount of debt that hangs over our heads and our children's heads. We will need financial assistance from the IMF and to get it the IMF will logically demand that we increase our potential output growth rate. To do that we will need to bring our RER down. To bring our RER down? Ding Ding Ding, we will inevitably need to devaluate our currency. Now we will also need to fiscally consolidate to rebuild a capital base that will form our basis of investment so that we can take 2 to 3 steps back to be able to take a much bigger leap forward. That is how it works always, the first few years are the hardest, because you need to cut consumption to increase your savings, but fairly quickly you'll be able to get to a much higher level of consumption that way. The government will still do everything it can to support the population to ensure population growth. But pensions will not move anymore, you have to realise that you got played hard, and you never got anything, they increased your pension on one side and printed money on the other side, effectively giving you a whole of disrespect but not much else in reality. If there is a need for it, because adequate nutrition is essential for all children so they can not only grow up healthy but live to their fullest potential be it education-wise, sports-wise or anything else, I will consider doing [SNAP](https://en.wikipedia.org/wiki/Supplemental_Nutrition_Assistance_Program) locally because it has too much literature going for it to deny its objective need to exist everywhere in the world, but that is it. But stop expecting too much from government. What you will get will be enough because inflation will go down and we will adopt a 2\% inflation regime. I am not going to lie to conglomerates either. Forget generous subsidies you have gotten from the current government. Stop expecting the state to be your daddy from now on. Get good to continue enjoying the privilege that god bestowed upon you or get lost. You will need to sell equity hereon, to raise any money when you need it. Your cost of capital will not be subsidised. All I need from you hereon is for you to have a real presence on world markets that stems from this country which brings in a shit ton of foreign currency through production. I do not care who it will be, whoever does it will receive a lot of support from the government at any scale. Cutthroat capitalism is what this country will turn into. The best will get everything. If you feel like you are the best, then you have nothing to be scared of.

We need to put a pin on Real Estate for now, and anything that has to do with services and 'beton' in general. You can continue to do it, just do not expect a single cent from the state. Besides healthcare reform where I will bring national health insurance in and we will do away with this 'free health-care' propaganda, services are just not something we can care about for now. I like South Korea's system of National Health Insurance and their way of working with the private sector. I do not like free stuff. Free stuff breeds complacency and an attitude where you do not feel the need to understand things. You are just given stuff in your lap basically which I do not like. I want people to feel like they have a right to complain to hospitals and want to empower them to be able to keep their public hospitals in check. To do that, you have to get rid of the propaganda word 'FREE'. Free generally means poor quality.  Nothing is free in this world. Now is that your experience of it too? So we get rid of it and rather start inculcating responsibility into our own. We need to encourage people to assert their rights when they pay for it with their tax money. Have you ever noticed, that we are a very passive bunch?  All of that passiveness stems from free stuff and things falling into people's lap. Are you curious as to why? Do you know what is the objective similarity between every societal structure that exists? Societal structures that are political, religious, social exist solely because they gamify the world we live in and thus allows for an efficient managing of chemicals in the brain with the big 4 being (Dopamine, Serotonin, Oxytocin, and Endorphins). Ergo consistent and predictable behaviors, patterns with the inevitable occasional chaos to it (crimes, accidents etc...). Socialism manages DOSE really well and turns you into well behaved children basically by giving you everything in your lap. Leaving that aside, our only focus is to have a real industrial base. Maybe some housing reforms here and there.

We need a capital intensive industrial base. How do we do that? That is a two-fold challenge. Of which the first is the need to secure enough domestic demand, because we do have not a lot of it clustered around here. But it is not doomed either, madagascar and reunion are a few hours away. We must pull these countries up by trading with them more and more and more. We must lobby France extensively in that it could be part of the African core if only it encouraged more people to move to Reunion and that there is a lot of tax and output to be had there. A lot. If between reunion and us, there were at least ~10-12 million people, and we added madagascar to that as well. We won. That is it. We are extremely safe from any conflict that will happen in the world because we have India, the US and France watching our backs. We are the safest place to do business in Africa for the next 100 years. Supply-side costs will only decrease with a competent government. We will however need to do good on our commitment to a few things, for the manufacturing to come. First is a commitment to population growth. Second is a commitment to free trade, maximum competition, and cutthroat capitalism. Third is a commitment to a stable democracy with sound government finances. Fourth is a commitment to find a pool of highly skilled workers. Number Fourth is by far the biggest challenge because we are dumb. We need some kind of free trade agreement with an advanced economy that has labor mobility eased into it so we can tap into a pool of highly skilled workers to develop a capital-intensive industrial base reliably. Eventually, it would also help us develop the financial side of it after all this is said and done. That is step two though and is a long way ahead. By that point, our current account will have turned into a current account surplus. There are many ways to try to coerce the world to come here, but I am not going to write each one down. I gave you the deterministic win condition. If we achieve it, then we will become the core of Africa. That should be enough of a plan for you for now.

## The Old Guard

You probably do not like these guys called the dinosaurs. How could you, they never gave really cared about you for 56 years, no matter what they say. You are probably disgusted by the labour party and want to give away your vote to someone else. I cannot tell you that I do not understand you because I have felt the exact same way too. That is why I decided to pick up my old dream and decided to commit to the labour party. Again I do not know if I will be accepted, so I guess the better analogy is I decided to get up on my ass and fight for my future myself because I finally realised that our country was filled with dumbducks. Most of the old guard are dumbducks. So what? Get the fuck up too and fight for the country you want to exist tomorrow. Get used to the fact that nobody cares. If you want something to happen, make it happen. Be the change you want to see in the world.

Look, let's be honest with ourselves, corruption has always been here, our parents just did not care about it. For us, it mattered much more because we grew up with the correct definition of democracy. Because we watched American and European tv shows, so we held our politicians to a much greater standard than our parents ever will when we judged them. All politicians of the old generation have fumbled. I cannot do anything about it. You cannot do anything about it. What do you want me to do kill them? Is that what you want? Then what? Ruin my life and yours because of some dumbasses? I am not a King. Just let it go. Leave the act of bestowing justice to god. Let's focus on reconstructing this country from scratch. For some reason, god has given them the opportunity to wash away their sins by liberating this country. So we can change our future together, by breaking this cycle of debasement and breaking away from being a dynasty. I know that permanently changing the future comes from the old guard letting go and retiring when we get to the second republic. Do not worry, put your trust solely in me henceforth, I will make good on that, I will ensure it but you have to understand that if you are in awe of me. Your parents for some reason that I do not understand and will probably never understand, are in awe of them. I cannot, not respect that if I am to do what is best for our country. We need them to transition into the Second Republic without a hitch. Without a war. We need to rally everybody around the labour party. For that to happen, we must all behave like true adults, true patriots and leave the arrogance behind. Accept our flaws. Humble ourselves and just do what is best for the betterment of all. 

Do you even realise how deep of a financial hole the country is actually in? You do not. I do. You cannot have pride right now. You have to act like an adult and compromise for your own good. For your children's own good tomorrow. So, tell me now, why should you penalise your own future, and the future of the Republic of Mauritius because of the actions of some dumbasses in a political party. That dumbass tomorrow could be me for all you know, I cannot predict the future. Look, these people have messed up. I admit it to you given they probably never will. But you cannot expect them to admit it to you given the law fumbled too. You have to accept that. Both times, for the coffre and the clinic. They could have gotten them but they rushed without being sure they had a solid case. You have to understand that prosecution is an art. When one commits a crime, there can be hundreds of potential charges that could be brought forward and prosecuted, rarely though will the hundred charges result in a conviction in the end. Most times you will only have a solid case for one or two charges at most. That is because Actus Reus, and Mens Rea conditions in White Collar crimes are ridiculously hard to prove beyond a resonable doubt. Your lovely state fumbled lots of such cases, either voluntarily or out of sheer stupidity. In any way, let it go. The FCC is an eyewash, it will not do anything concrete, it exists solely to do smear campaigns that will never turn into anything, and you should rather wonder if its budget is being used to fund elections. In Nazi Germany, its FCC was called the Ministry of Propaganda. It solely exists to fool your parents who trust government agencies as gospel as did Germans back in the day.

So to sum up, these people we the young generation dislike, they command the vote of a lot of the elderly people (50+). The likelihood of your parents understanding what I have written here is less than 10\%. Your parents will not understand the maths or what indoctrination is. They will not understand reason. Do not bother them. Do not pester them. Just respect your parents. Be grateful that they are in your life. What we will do rather is to use these people as they used our parents, we will use them as our crutch. You should not expect me to become the leader of the labour party overnight. Do you even realise how honest I have been with you in these papers? You know more about me than literally anybody in my actual life. Clearly, I am a bad politician, given how honest I have been with you. I kid you of course, but you know do not expect change overnight, change will come. I am here now. I will dedicate the rest of my life to turning this island into a true paradise minus the communalism. But political parties are not really parties on this island. The first thing is to turn the labour party into a real political party and cut the inbreeding. That is not easy. Luckily there are more of you than the elderly and your number will only increase hereon. So if you want that precious democracy of yours to spread everywhere like wildfire going forward. Let it be written on all the walls, shouted in all the streets of our soon to be Republic, let it be goddamn known, who alone holds your vote now. Be proud and exclaim with pride that it is the future President of The Second Republic of Mauritius, Yuuki. And always remember if you want to lead this country one day. You are not allowed to be a pussy. You have to be bold and honest about things, dare talk of them as they are, so change can happen. You have to understand the world you live in better than anybody, so you can confront your people with the reality they live in. You have to be ready to empower the new by destroying the old if need be, so the new can come in and bud wonderfully free of the shackles of the past, that was holding it back. You have to be willing to carry that heavy burden. Every mistake will be yours and every success is the country's. Be the real deal however, and the country will reward you by attributing all its success to you in return, without you asking. Last but not least, always remember that no matter what is happening, what has happened, no matter the hardship, the circumstance, the crimes, he is always by your side and that is your [solace and salvation](https://www.youtube.com/watch?v=rSYoIuyks8g).


:::{.text-center}
May God bless our new found unity as a United Mauritius
:::